In [10]:
#1. Test whether none of elements of an array is zero
import numpy as np
x= np.array([2,8,5,0])
print(x)
print(np.all(x))

[2 8 5 0]
False


In [11]:
#2. Test whether none of elements of an array is non-zero
import numpy as np
x= np.array([2,8,5,0])
print(x)
print(np.any(x))

[2 8 5 0]
True


In [18]:
#3.  Create an element-wise comparison (equal, equal within a tolerance) of two numpy arrays
import numpy as np
x= np.array([2,8,5,0])
y= np.array([2,8,7,9])
print(x)
print(y)
print("Equal:",np.equal(x, y))
print("Equal within a tolerance:", np.allclose(x, y))

[2 8 5 0]
[2 8 7 9]
Equal: [ True  True False False]
Equal within a tolerance: False


In [21]:
#4. Create an array of 10 zeros,10 ones, 10 fives
import numpy as np
x= np.zeros(10)
print("An array of 10 zeros:", x)
y= np.ones(10)
print("An array of 10 ones:",y)
z= np.zeros(10)+5
print("An array of 10 fives:", z)

An array of 10 zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives: [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [22]:
#5. Create an array of the integers from 30 to70.
import numpy as np
x= np.arange(30,71)
print(x)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [24]:
#6. Create a 3x3 identity matrix 
import numpy as np
x= np.identity(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [30]:
#7. Generate a random number between 0 and 1
import numpy as np
x = np.random.normal(0,1,1)
print(x)

[0.03415644]


In [32]:
#8. Generate an array of 15 random numbers from a standard normal distribution
import numpy as np
x = np.random.normal(0,1,15)
print(x)

[ 0.97430545  1.03428437  0.62908285 -0.06753185 -1.08570531 -0.43279727
  2.04598896  0.00711545  1.04769486 -0.30231793  0.99253013 -0.95303678
  1.15688283  0.80854545  0.46430387]


In [38]:
#9. Create a vector with values ranging from 15 to 55 and print all values except the first and last
import numpy as np
x= np.arange(15,55)
print(x)
print("All except first and last:", x[1:-1])

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]
All except first and last: [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


In [49]:
#10. Create a vector of length 5 filled with arbitrary integers from 0 to 10 
import numpy as np
x= np.random.randint(0, 11, 5)
print(x)

[ 8  9  2  7 10]


In [48]:
#11. Create a 10x10 matrix, in which the elements on the borders will be equal 1 and inside 0
import numpy as np
x= np.ones((10, 10))
x[1:-1, 1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [47]:
#12. Create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5
import numpy as np
x= np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [46]:
#13. Create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal
import numpy as np
x= np.zeros((4, 4))
x[::2, 1::2] = 1
x[1::2, ::2] = 1
print(x)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


In [52]:
#14. Save two given arrays into a single file in compressed format (.npz format) and load it
import numpy as np
import os
x= np.arange(10)
y= np.arange(11, 20)
print(x)
print(y)
np.savez('temp.npz', x=x, y=y)
with np.load('temp.npz') as data:
    x2 = data['x']
    y2 = data['y']
    print(x2)
    print(y2)

[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]
[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]


In [53]:
#15. Create a one-dimensional array of forty pseudo-randomly generated values
import numpy as np  
np.random.seed(10)
print(np.random.rand(40))

[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665
 0.19806286 0.76053071 0.16911084 0.08833981 0.68535982 0.95339335
 0.00394827 0.51219226 0.81262096 0.61252607 0.72175532 0.29187607
 0.91777412 0.71457578 0.54254437 0.14217005 0.37334076 0.67413362
 0.44183317 0.43401399 0.61776698 0.51313824 0.65039718 0.60103895
 0.8052232  0.52164715 0.90864888 0.31923609 0.09045935 0.30070006
 0.11398436 0.82868133 0.04689632 0.62628715]


In [65]:
#16. Extract all numbers from a given array which are less and greater than specified number
import numpy as np  
x= np.array([[5.54, 3.38, 7.99],
              [3.54, 4.38, 6.99],
              [1.54, 2.39, 9.29]])
print(x)
n= 5
print("Elements greater than",n,"are",x[x > n])
print("Elements less than",n,"are",x[x < n])

[[5.54 3.38 7.99]
 [3.54 4.38 6.99]
 [1.54 2.39 9.29]]
Elements greater than 5 are [5.54 7.99 6.99 9.29]
Elements less than 5 are [3.38 3.54 4.38 1.54 2.39]
